import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import format from 'date-fns/format'

const Home: NextPage = () => {

  const today = new Date();

  const bookingDays = [];
  const resources = ["Vask 1", "Vask 2", "Tørk"]
  const timeSlots = ["00-01","01-02","02-03","03-04","04-05"]

  for(let i = 0; i < 7; i++ ) {
    bookingDays.push(new Date(today.setDate(today.getDate() + 1)))
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {
          bookingDays.map(date => {
            return (
              <div key={date.getDate()} tabIndex={0} className="collapse border rounded-box border-base-300 collapse-arrow show">
                <input type="checkbox" />
                <div className="collapse-title text-xl font-medium flex justify-between"><div>{format(date, "EEEE")}</div><div>{format(date, "dd-MM-yyyy")}</div></div>
                <div className="collapse-content">
                  <table className="table w-full">
                    <thead>
                      <tr>
                        <th>Time</th>
                        {resources.map(resource => <th key={"resourceheader-" + resource}>{resource}</th>)}
                      </tr>
                    </thead>
                    <tbody>
                      {timeSlots.map((timeSlot => {
                        return (
                          <tr key={"timeslot-"+timeSlot}>
                            <td className="max-w-sm">{timeSlot}</td>
                            {resources.map(resource => <td key={resource}><button className="btn btn-xs color-white">{resource}</button></td>)}
                          </tr>
                        )
                      }))}
                    </tbody>
                  </table>
                </div>
              </div>
            )
          })
        }
      
      </main>
    </div>
  )
}

export default Home
