import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import format from 'date-fns/format'

const Me: NextPage = () => {

  const today = new Date();

  const bookings = [
    {
      date: new Date(),
      timeSlot: "03:00-04:00"
    },
    {
      date: (new Date()).setDate(new Date().getDate() + 3),
      timeSlot: "16:00-17:00"
    },
    {
      date: (new Date()).setDate(new Date().getDate() + 5),
      timeSlot: "16:00-17:00"
    },
    {
      date: (new Date()).setDate(new Date().getDate() + 7),
      timeSlot: "18:00-19:00"
    }
  ]


  return (
    <div className={styles.container}>
      <Head>
        <title>Profil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-xl font-semibold w-full text-center my-10">Mine bookinger</h1>
        {
          bookings.map(booking => {
            return (
              <div key={booking.date + booking.timeSlot} className="flex justify-between p-2 my-2 align-middle border-2 border-gray-300">
                <div className="flex">
                  <div className="flex justify-between font-semibold">
                    <div className="">{format(booking.date, "EEEE")}</div><div className="ml-2">{format(booking.date, "dd-MM-yyyy")}</div></div>
                    <div className="ml-2">{booking.timeSlot}</div>  
                </div>
                <button className="btn btn-warning btn-sm">Slett</button>
              </div>
          )})
        }
      
      </main>
    </div>
  )
}

export default Me
